### PR TITLE
Fix inconsistent line endings in tests

### PR DESCRIPTION
**Pull request by jamesfoster**

### CODE REVIEW

**Comment by shocklateboy92** [comment]
@jamesfoster what exactly is this for? Could you clarify a little what you mean by "inconsistent line endings"?

**Comment by jamesfoster** [comment]
https://github.com/belav/csharpier/issues/1240#issuecomment-2122589506

I explain in this comment

After a clean checkout of the repo on windows, several tests fail because of line ending mismatches.

**Comment by jamesfoster** [comment]
Also notice these checks are failing. I turned on csharpier formatting on save but clearly missed a file somewhere. I'll reformat and update the branch with main later today

**Comment by jamesfoster** [comment]
Apologies for the delay. I had a hectic weekend. Will get to this today.

**Comment by jamesfoster** [comment]
Rebased onto belav/csharpier@bc331cdd079c5963a398dc728b54b15264dbfd7f

**Comment by jamesfoster** [comment]
@shocklateboy92 @belav  There is still one test that fails for me locally.

https://github.com/belav/csharpier/blob/bc331cdd079c5963a398dc728b54b15264dbfd7f/Src/CSharpier.Cli.Tests/CliTests.cs#L118-L131

The exit code is `0` for me but the test asserts it should be `1`. Any ideas?

**Review by shocklateboy92 — APPROVED** [review]
LGTM. Thanks for your contribution.

**Comment by jamesfoster** [comment]
@belav https://github.com/belav/csharpier/pull/1288#issuecomment-2173777372
Can I get your thoughts on why `Should_Return_Error_When_No_DirectoryOrFile_And_Not_Piping_StdIn` might be failing for me?

**Comment by shocklateboy92** [comment]
Hey @jamesfoster, sorry I rudely completed the PR to get it off my queue :stuck_out_tongue: 

As for your issue, you can run the test locally with a debugger breakpoint and see if it reaches this validator:
https://github.com/belav/csharpier/blob/75a582ba575ff46ab76abb801d8be411df574767/Src/CSharpier.Cli/CommandLineOptions.cs#L101

**Comment by jamesfoster** [comment]
Thanks @shocklateboy92 I'll look into it

**Comment by pisolofin** [comment]
I have the same issue.
In Debug of Test I can reach only, after `The breakpoint will not currently be hit. No symbols have been loaded for this document.`
https://github.com/belav/csharpier/blob/75a582ba575ff46ab76abb801d8be411df574767/Src/CSharpier.Cli.Tests/CliTests.cs#L561

The result is:
image

Can @jamesfoster halp me?

Thanks.

**Pull request merged**
