### PR TITLE
Only wait 3 seconds for csharpier to format, otherwise kill it and restart it.

### LINKED ISSUE #926: Chsarpier freezes Rider
When I refactor Code, Csharpier freezes the UI sometimes.
Unfortunately it's impossible to reproduce reliably.
It mostly happens when I reformat code and the code is broken for a moment.

Can I find logs somewhere?

Usually killing the Csharpier Task via Taskmanager and then reenabling the Plugin unfreezes the Ui.

### PR DESCRIPTION
**Pull request by belav**
closes #926

### CODE REVIEW

**Review by shocklateboy92 — APPROVED** [review]
Uh... do you know _why_ the csharpier process hangs? 
Are we using synchronous waits? deadlocks? 

Maybe it's worth some more investigation before jumping to a workaround?

**Comment by belav** [comment]
> Uh... do you know _why_ the csharpier process hangs? Are we using synchronous waits? deadlocks?
> 
> Maybe it's worth some more investigation before jumping to a workaround?

We aren't really sure, and I've only seen it maybe once a week or so, with nothing in the logs to help figure out wtf is going on. The VS plugin has basically the same code to kill hung processes so it seemed safe enough. Maybe someone else that saw it more often could be convinced to fire up the plugin in debug, otherwise I'm not really sure how to track down the problem.

**Comment by shocklateboy92** [comment]
> > Uh... do you know _why_ the csharpier process hangs? Are we using synchronous waits? deadlocks?
> > Maybe it's worth some more investigation before jumping to a workaround?
> 
> We aren't really sure, and I've only seen it maybe once a week or so, with nothing in the logs to help figure out wtf is going on. The VS plugin has basically the same code to kill hung processes so it seemed safe enough. Maybe someone else that saw it more often could be convinced to fire up the plugin in debug, otherwise I'm not really sure how to track down the problem.

So, logs probably won't help you in tracking down a deadlock. You have to take a memory dump when that happens and look at the stacks:
https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-deadlock

**Comment by belav** [comment]
I have a little bit of experience with dumps, but more around memory usage.

Based on the most recent comment on the freezing ticket, it could be that when a file is in just the wrong state, the streaming of data back and forth between the plugin and csharpier gets into a stuck state because one of the delimiters on either end never gets sent. It is probably about time to switch over to something like protobuf. I should also modify this to keep track of the file that fails when it hangs.

**Pull request merged**
