### PR TITLE
Reimplement CLI Commands to SubCommands

### PR DESCRIPTION
**Pull request by stefannikolei**
I started working on creating subcommands. 

Could I get feedback for this? Is this the direction you want it to go?

It would be good for me when we could define all commands with the possible options

### CODE REVIEW

**Comment by belav** [comment]
> Could I get feedback for this? Is this the direction you want it to go?

I only had time to scan it quick, but yeah I this looks like what I was thinking, breaking apart the commands so it is clear which options apply to which command.

**Comment by stefannikolei** [comment]
Ok i am finished. You could go for a review. One thing I was not sure about was which option should be available for the check command.

**Review by shocklateboy92 — APPROVED** [review]
LGTM. I'm going to let @belav do the final merge though.

**Review by belav — APPROVED** [review]
I'm not totally sure what options are needed for check, I'm guessing there will be a few from format that need to be added to check. Probably these three

```
--no-msbuild-check
--include-generated
--compilation-errors-as-warnings
```
It is also possible that `--no-cache` would apply.

I can always merge for now and figure it out later unless you wanted to take it on in the same PR. Sorry for the delay in getting back to this, and thanks for the contribution!

**Comment by stefannikolei** [comment]
As you want. You can also ping me when you figured it out.

**Comment by belav** [comment]
Got the last few sub options cleaned up and settled on just making a new branch for 1.0.0 instead of waiting to merge this to main. Thanks again!

**Pull request merged**
