### PR TITLE
Ignore .editorconfig file included in the .csharpierignore file

### PR DESCRIPTION
**Pull request by sebastieng84**
This will resolves issue #1023.

Any .editorconfig file included in the .csharpierignore file will not be parsed. By default we ignore everything in node_modules, but it still tries to parse the .editconfig file.

### CODE REVIEW

**Comment by shocklateboy92** [comment]
Looks like there are some formatting issues

**Comment by shocklateboy92** [comment]
@sebastieng84 please format the files locally with CSharpier and commit the result when you have some time so we can merge this.
#1039 will most likely cause merge conflicts with this, if you can fix this soon I'd like to merge this before @belav's PR.

**Review by belav — APPROVED** [review]
I went ahead and formatted, everything else looks good. Thanks for the contribution!

**Comment by sebastieng84** [comment]
@belav sorry my kid has been sick and I didn't get the chance to fix the formatting! Thanks for fixing it 🙏

**Pull request merged**
