### PR TITLE
Strong name sign assemblies

### PR DESCRIPTION
**Pull request by belav**

### CODE REVIEW

**Comment by shocklateboy92** [comment]
Since you're pulling in the Ignore library, I would recommend against integrating the logic into our project.

Instead, create a top level directory called 'lib` or `External` or `Dependencies` or something.
When you put the ignore library in there, you should very clearly write down the version (or ideally, commit hash) that you're pulling from. You will definitely want to refer to this in future when taking updates of Ignore in future.
Maybe you can use git submodules, if the file structure of their repo doesn't need to change much.

That however, is a backup plan. My strongest suggestion is to have @TwentyFourMinutes (seems I can't tag him directly out side of issue #911 ) to follow up with the owner of the Ignore library and get them to sign their package. Then we can continue taking security fixes / updates from them via nuget, and allow ours to be used by signed only projects.

**Comment by TwentyFourMinutes** [comment]
That's fine by me. 👍

**Comment by TwentyFourMinutes** [comment]
https://github.com/goelhardik/ignore/issues/36

**Comment by belav** [comment]
> [goelhardik/ignore#36](https://github.com/goelhardik/ignore/issues/36)

I assumed because the project hadn't been updated for a while it would take a while for it to be updated, the quick response on it was awesome to see!

**Comment by TwentyFourMinutes** [comment]
You are god damn right, that's quite nice to see!

**Review by shocklateboy92 — APPROVED** [review]
LGTM

**Pull request merged**
