### PR TITLE
VSCode Extension: Add diagnostics and code actions

### LINKED ISSUE #659: Format only the selected code
Hello team, here with a feature request. 

In most cases, we don't want to format the whole class but certain complex parts of the code. With this in mind, it would be super useful if formatting would be possible only on the selected part of the code.

Please look into the possibility of this implementation.

Thanks in advance! 🤞

### LINKED ISSUE #1375: VSCode Exension Proposal: Diagnostics and Code Actions
Hi. It would be great if the VSCode extension provided diagnostic and code actions to:

- highlight inline foratting issues
- add code actions to format individual parts of code

For example:

Screenshot 2024-11-07 at 21 55 03

Is this something you'd be interested in? I have already have this working in my fork and i'll send a PR soon.

### PR DESCRIPTION
**Pull request by badsyntax**
Fixes #1375
Fixes #659

A lot of this code has been taken from [one of my open source extensions](https://github.com/badsyntax/vscode-spotless-gradle). 

This approach uses the [prettier-linter-helpers](https://www.npmjs.com/package/prettier-linter-helpers) package to generate diffs of strings (unformatted code against formatted code) which is used to provide diagnostic information and code actions. This allows for formatting parts of code. 

Screenshot 2024-11-07 at 21 55 03
Screenshot 2024-11-07 at 22 26 38

### CODE REVIEW

**Review by shocklateboy92 — COMMENTED** [review]
Hey, thanks for your contribution! It was a pretty neat idea to do the comparison in VSCode instead of CSharpier. It won't help for other IDE integrations, but I suppose this it better than nothing.

You mentioned that it fixes #659, but from looking through the code I only see a new code action provider being created. 

Will this code make partial formats happen if
```json
"editor.formatOnSaveMode": "modificationsIfAvailable"
```
is set?

If not, would you be able to make a simple change to add it?

**Comment by badsyntax** [comment]
Hey, apologies for the delay in responding.

> You mentioned that it fixes https://github.com/belav/csharpier/issues/659, but from looking through the code I only see a new code action provider being created.

Yes sorry, I have not thought about Format Selection. By [providing a QuickFIx CodeAction](https://github.com/badsyntax/csharpier/blob/6b7d2391482ec69fc5a44be943e4808eec611673/Src/CSharpier.VSCode/src/DiagnosticsService.ts#L208-L226) it's possible to format only parts of the code. While not the same as formating selection it provides a similar feature:

https://github.com/user-attachments/assets/a7145741-7a58-4025-9339-c2ee34cbbb7f

Saying that, I will investigate to see how complicated it'l be to support Format Selection.

> Will this code make partial formats happen if  "editor.formatOnSaveMode": "modificationsIfAvailable"

At this time it doesn't support `modificationsIfAvailable` but I'll see if I can support that.

**Comment by badsyntax** [comment]
OK! With the latest change we can format selection.

We generate the diff, then we compare the differences to check if they're in the range of the selection, and if so, apply the diff change as a TextEdit.

https://github.com/user-attachments/assets/614475dc-cba5-40ba-b52a-bc797f9fa38e

**Comment by badsyntax** [comment]
Also, now that we can format within a range, `"editor.formatOnSaveMode": "modificationsIfAvailable"` & `"editor.formatOnSaveMode": "modifications"` is now working:

https://github.com/user-attachments/assets/3a98d8ee-afc4-4a7d-980a-77c5ebbb9237

**Review by shocklateboy92 — APPROVED** [review]
LGTM. Thank you very much for your contribution!

**Comment by belav** [comment]
@badsyntax thanks for implementing all of this! Sorry for the delay on releasing it, I published version 1.9.0 just now which contains the changes.

**Comment by badsyntax** [comment]
@belav awesome. Code is pretty easy to follow imo but feel free to ping me for any modifications/support

**Pull request merged**
